### ISSUE TITLE
Review Setup Guide

### ISSUE THREAD

**Issue by joaopedroo5** [VMormoris/tw2-stats#8]
With the commit #6 I believe you allowed using the application for multiple world.
With that you missed to update the Setup Guide in order to run file "database/tw2-stats_db_creation.sql"

P.s: This is my first issue, so take it with a bit of salt and help me improve 👍 

-- Edit
Added print screens of the problems that I believe where introduced with the commit.
![image](https://user-images.githubusercontent.com/28655654/169678875-0782df43-f2e0-42e5-9a30-e544fe008e2c.png)

**Comment by VMormoris** [comment]
You are right when I merged the pull request #6 (World Overview), I forgot to update the Setup Guide. I will fix it but it might take a little while because right now I'm experimenting with ```docker``` which is suppose to make the setup process a lot easier (but it will require for me to rewrite the setup guide basically from scratch).

As far as the support for multiple worlds, the application was build from the start in a way that is suppose to support multiple worlds. But they are two big caveats at the moment:
* The website's UI doesn't have a way for you to navigate between worlds.
* The ```dumper-app``` (aka the program that pulls the data for the website) has some bugs that need to be fixed before properly deploying for multiple worlds.

_Both of the issues that I described above, I'm planning to solve with the next update._

By the way since you are the first one that was trying the Setup Guide.
Do you have any other idea about things that are missing or anything else that will make it better?

**Comment by joaopedroo5** [comment]
I had no problems following the setup guide. It was simple and gave me clear instructions on what I was required to do.

Since you probably will take a while expediting the application to docker, maybe you could say what we need to do to solve this in a simplistic way (comment), about what we need to do to keep the application running.

I've got to say, that I was happy to see someone interested on this, since is a fundamental toll many players, myself included use daily.
